### PR TITLE
Create a model hook around the lockable warden hook to reset attempts

### PR DESCRIPTION
**Pull request by carlosantoniodasilva**
Resetting failed attempts after sign in happened inside a warden hook
specific for the lockable module, but that was hidden inside the hook
implementation and didn't allow any user customization.

One such customization needed for example is to direct these updates to
a write DB when using a multi-DB setup. With the logic hidden in the
warden hook this wasn't possible, now that it's exposed in a model
method much like trackable, we can override the model method to wrap it
in a connection switch block for example, point to a write DB, and
simply call `super`.

Closes #5310
Related to #5264 and #5133

### CODE REVIEW

**Review by geoffharcourt — APPROVED** [review]
Awesome. Thank you for taking this on, my apologies for not getting to it sooner! I think this change will help a lot of Rails 6 users with a replica database setup.

**Comment by mhenrixon** [comment]
This looks great and not as complicated as I thought it would be. Kudos for tackling this problem! It is the one thing that prevents me from making full (and easy) use of the replica reads.

**Comment by geoffharcourt** [comment]
We've been using this change in production and haven't seen any exceptions from attempting to write to the read-only replica since applying it.

**Comment by carlosantoniodasilva** [comment]
Thanks @geoffharcourt @mhenrixon, this is now on master and will be on the next release, which I'm hoping to cut soon.

**Comment by paulspringett** [comment]
Hey @carlosantoniodasilva Please could I ask when you're planning on the next release to RubyGems? I've just come across this as we're looking for a fix to this issue with Rails 6.1 multi-database switching. Many thanks!

**Comment by carlosantoniodasilva** [comment]
I just pushed v4.8 including this change, please give it a try and report back if you have any issues. Thanks.

**Comment by paulspringett** [comment]
@carlosantoniodasilva Thanks so much, really appreciate it 🙌

**Pull request merged**
