### PR TITLE
Fixing Zeitwerk errors when running Devise without ActionMailer

### PR DESCRIPTION
**Pull request by aldent95**
This fixes the longstanding issue #5140 where Zeitwerk throws errors around when using Devise without ActionMailer.

Overall behaviour shouldn't be effected. The new empty class is only used when the application would otherwise error our (ActionMailer not available and Zeitwerk enabled)

### CODE REVIEW

**Comment by lxxxvi** [comment]
What is the use for `.zeitwerk_enabled?` clause in the first place? Wouldn't it be possible just to have the empty class if `ActionMailer` is not there?

`.zeitwerk_enabled?` was introduced around Rails 6.0 and devise is backward compatible with Rails 4 (I guess), so this condition may cause issues in earlier versions.

**Comment by lomefin** [comment]
Is there any real damage if it just defines the class if ActionMailer is not defined?
I understand that adding the rule makes it more focused on solving the error.
But it adds a new dependency, so now we don't need ActionMailer but we need Zeitwerk.

I added `Devise::Mailer` on an initializer and seems to work alright.

If possible, I would just define the class and leave it empty if there is no ActionMailer

**Comment by rafaelfranca** [comment]
Would devise even work without Action Mailer? So many of its default modules requires a mailer to exist.

Can you provide how you are planning to use Devise without a mailer?

**Comment by Fs00** [comment]
@rafaelfranca In the company I work for, we are using Devise without Action Mailer in a Rails app that powers an internal portal where users log in via LDAP. In that scenario we don't need mailers at all, since user registration/user blocking/password change are all handled by AD.

**Comment by nashby** [comment]
@aldent95 thank for PR! I've just merged https://github.com/heartcombo/devise/pull/5731 with a bit different approach.

**Pull request closed without merging**
