### PR TITLE
Removed now obsolete SecretKeyFinder

### PR DESCRIPTION
**Pull request by BroiSatse**
SecretKeyFinder was required to handle rails configuration pre 6.0 which is no longer supported. Secret key can (and should!) be now read directly from rails application.

Fixes: https://github.com/heartcombo/devise/issues/5644
Probably surpasses: https://github.com/heartcombo/devise/pull/5604

### CODE REVIEW

**Comment by dgm** [comment]
The best bugfix is one that removes code. :)

**Comment by issei-m** [comment]
Any news?

**Comment by grk** [comment]
For those looking for a workaround, you can set the secret key in your `devise.rb` initializer:
```ruby
config.secret_key = Rails.application.secret_key_base
```
and you won't see the deprecation warning anymore.

**Comment by jordan-brough** [comment]
Would be nice to have this published. cc @carlosantoniodasilva? 🙏

**Comment by jcoyne** [comment]
Yes! I was just about to submit a similar change, but you went a step further. 👍

**Comment by albus522** [comment]
It is probably worth noting somewhere that this is a potentially breaking change. As I noted in #5634, Rails and Devise use a different priority order in what they choose. For certain old app configurations this could result in the key unintentionally changing.

**Comment by dan-jensen** [comment]
@albus522 good call. And we could even consider this a bugfix, because Devise shouldn't have been choosing a different key than the application. Seems like bumping the version to 4.10 and noting this breaking change in [CHANGELOG.md](https://github.com/heartcombo/devise/blob/main/CHANGELOG.md) would be sufficient.

**Comment by bbuchalter** [comment]
It looks like this PR lost momentum and still addresses an open issue. What's needed to move it forward?

**Comment by nashby** [comment]
Thanks everyone!

**Pull request merged**
