### PR TITLE
Fix hanging tests for streaming controllers using Devise

### LINKED ISSUE #5285: Devise tests hang when a controller using ActionController::Live calls authenticate_user!
## Current behavior

Given a streaming controller that uses `authenticate_user!`:

```ruby
class MyController < ApplicationController
  include ActionController::Live
  before_action :authenticate_user!
  ...
end
```

controller tests will hang when authentication fails. This is because `#_process_unauthenticated` is setting the response body with `@controller.response.body=` rather than `@controller.response_body=`. The subtle difference is that ActionController::Live [overrides](https://github.com/rails/rails/blob/ee6ee11b01dd8259ab2e8998d8d4984ddf39e340/actionpack/lib/action_controller/metal/live.rb#L280) `@controller.response_body=` to close the stream after setting the body; if the stream isn't closed, the thread will hang indefinitely.

## Expected behavior

Does not hang indefinitely. :)

I've got a PR coming in a few minutes.

### PR DESCRIPTION
**Pull request by afn**
Fixes #5285.

### CODE REVIEW

**Comment by afn** [comment]
Whoops! In Rails 6 (and 5), #2332 doesn't impact controller tests, but apparently in Rails 4 it does. Should be fixed now.

**Comment by carlosantoniodasilva** [comment]
:+1: thanks!

**Comment by afn** [comment]
Any idea when this will be released (to rubygems, that is?)?

**Comment by carlosantoniodasilva** [comment]
I don't have an ETA, but it looks like I'll have to cut something soon ;)

I had someone asking: https://github.com/heartcombo/devise/issues/5252#issuecomment-691989588, but I have to check on a couple other things first in regards to what's in master. Hopefully 🔜

**Comment by carlosantoniodasilva** [comment]
@afn v4.7.3 is out including this change, thanks!

**Pull request merged**
